export const vehicleClasses = [
    'Compact',
    'Sedans',
    'SUVs',
    'Coupes',
    'Muscle Cars',
    'Classic Sports Cars',
    'Sports Cars',
    'Supercars',
    'Motorcycles',
    'Off-road Vehicles',
    'Industrial',
    'Utility',
    'Vans',
    'Bicycles',
    'Boats',
    'Helicopters',
    'Airplanes',
    'Service Vehicles',
    'Emergency Vehicles',
    'Military Vehicles',
    'Commercial Vehicles',
    'Trains',
    'Open-top Vehicles',
];